# Generated by Selenium IDE
import allure
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestMyFirstTestCase:
    def setup_method(self, method):
        # options = Options()
        options = webdriver.ChromeOptions()
        self.driver = webdriver.Remote(
            command_executor="http://localhost:4444/wd/hub", options=options
        )
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    @allure.step("Open the RPACHallenge website")
    def open_website(self):
        self.driver.get("https://rpachallenge.com/")

    @allure.step("Set window size")
    def set_window_size(self):
        self.driver.set_window_size(1936, 1048)

    @allure.step("Fill in the form")
    def fill_form(self):
        self.driver.find_element(
            By.XPATH,
            "(.//*[normalize-space(text()) and normalize-space(.)='Role in Company'])[1]/following::input",
        ).click()
        self.driver.find_element(
            By.XPATH,
            "(.//*[normalize-space(text()) and normalize-space(.)='Role in Company'])[1]/following::input",
        ).send_keys("Senior QA Engineer")
        self.driver.find_element(
            By.XPATH,
            "(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::input",
        ).click()
        self.driver.find_element(
            By.XPATH,
            "(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::input",
        ).send_keys("Naftaly")
        self.driver.find_element(
            By.XPATH,
            "(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::input",
        ).send_keys("1 first Street, City One, IL")
        self.driver.find_element(
            By.XPATH,
            "(.//*[normalize-space(text()) and normalize-space(.)='Phone Number'])[1]/following::input",
        ).send_keys("03-12345678")
        self.driver.find_element(
            By.XPATH,
            "(.//*[normalize-space(text()) and normalize-space(.)='Last Name'])[1]/following::input",
        ).send_keys("Shprai")
        self.driver.find_element(
            By.XPATH,
            "(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/following::input",
        ).send_keys("NOTL")
        self.driver.find_element(
            By.XPATH,
            "(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::input",
        ).send_keys("test1@gmail.com")

    @allure.step("Submit the form")
    def submit_form(self):
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()

    def test_myFirstTestCase(self):
        # Test name: MyFirstTestCase
        self.open_website()
        self.set_window_size()
        self.fill_form()
        self.submit_form()


"""
1. Install Allure Pytest Plugin
   pip install allure-pytest

2. Install Allure Command Line Tool
   2.1 Download Allure Command Line Tool
       https://github.com/allure-framework/allure2/releases
       ( Download the appropriate version for your operating system. For example, you can download the zip file for Windows )

   2.2 Extract the downloaded zip file to a preferred location on your machine
   2.3 Add Allure to System PATH ( Add the bin directory of the extracted folder to your system's PATH environment variable )


3. Modify Your Test Script to Use Allure

4. Running Tests with Allure
   pytest --alluredir=allure-results
   Or
   pytest test_myFirstTestCase-with-Allure-reporting.py --alluredir=allure-results

5. Generate and View Allure Report
   allure serve allure-results

6. Merging allure test results
   @echo off
   setlocal EnableDelayedExpansion

   :: Initialize the allure generate command
   set "allureGenerateCommand=allure generate"

   :: Loop from 1 to 10 to build the allure generate command with all directories
   for /L %%i in (1,1,10) do (
       set "allureGenerateCommand=!allureGenerateCommand! allure-results-%%i"
   )

   :: Add the output directory for merged results
   set "allureGenerateCommand=!allureGenerateCommand! -o merged-results"

   :: Execute the constructed generate command
   echo Running: !allureGenerateCommand!
   !allureGenerateCommand!

:: Serve the merged results
echo Serving merged results...
allure serve merged-results



"""
